name: test-workflow
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: create private key file
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "ssh-1.pem"
        FILE_DATA: "${{ secrets.SSH_PRIVATE_KEY }}"
    
    - name: verify key 1
      run: ls -al . 
    
    - name: verify key 2
      run: cat ssh-1.pem


    - name: install python
      uses: actions/setup-python@v1

    - name: install ansible
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          ansible
          boto
          boto3
                
    - name: run ansible-playbook
      run: ansible-playbook aws-ec2-ubuntu.yml --extra-vars "aws_access_key=${{ secrets.AWS_ACCESS_KEY }} aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"

    - name: upload test reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
      with:
        name: reports
        path: output
